### ISSUE TITLE
'Invalid branch name' on cloning the repo

### ISSUE THREAD

**Issue by jalal** [lightningdevkit/ldk-sample#88] opened 2022-12-29 16:53 UTC
Trying to clone the repo with:
`git clone https://github.com/lightningdevkit/ldk-sample`
gives the error:
```
Cloning into 'ldk-sample'...
fatal: invalid branch name: init.defaultBranch = 
```
Necessary to download and unpack the source zip file.

**Comment by tnull** [comment] 2023-01-02 17:48
As the given command works without issue for me, I think this is not a bug, but likely has to do with your local git config. Could it be that you have the `init.defaultBranch` value overridden with something else than `main`?

Closing for now.

**Closed by tnull** 2023-01-02 17:48 UTC

**Comment by jalal** [comment] 2023-01-05 19:10
you were correct!
